name: ci-cd

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Teste com maven
        run: mvn clean test -Ptest
      - name: Build com maven
        run: mvn clean package -Pprod
      - name: Build the docker image
        run: docker build -t ogabrielsantoos/backend:auth-server .
      - name: Log in docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push no docker hub
        run: docker push ogabrielsantoos/backend:auth-server
  deploy:
    needs: build
    runs-on: [ self-hosted, auth-server ]
    steps:
      - name: Pull Docker image
        run: docker pull ogabrielsantoos/backend:auth-server
      - name: Stop Docker Container
        run: docker stop auth-server || true
      - name: Remover container
        run: docker rm auth-server || true
      - name: Run Docker Container
        run: docker run --name auth-server -d -p 8080:8080 ogabrielsantoos/backend:auth-server